# Generated by Django 3.1.7 on 2021-03-27 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0002_body_createdat_id_likecount_name_updatedat'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Name',
            new_name='User',
        ),
        migrations.DeleteModel(
            name='CreatedAt',
        ),
        migrations.DeleteModel(
            name='Id',
        ),
        migrations.DeleteModel(
            name='LikeCount',
        ),
        migrations.DeleteModel(
            name='UpdatedAt',
        ),
    ]
