# Generated by Django 3.1.7 on 2021-03-27 22:25

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0003_auto_20210327_1714'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('like_count', models.IntegerField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=14)),
                ('body', models.CharField(max_length=140)),
            ],
        ),
        migrations.DeleteModel(
            name='Body',
        ),
        migrations.DeleteModel(
            name='Picture',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
