# Generated by Django 3.1.7 on 2021-03-27 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0005_auto_20210327_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='like_count',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
