# Generated by Django 3.1.7 on 2021-03-31 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0007_auto_20210330_2255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='like_count',
            field=models.ManyToManyField(related_name='_tweet_like_count_+', to='twitter.Tweet'),
        ),
    ]
