# Generated by Django 3.1.7 on 2021-04-01 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0008_auto_20210331_0000'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweet',
            name='like_count',
        ),
        migrations.AddField(
            model_name='tweet',
            name='like_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
